### ISSUE TITLE
Attempt to revise entity definitions and controllers

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entityform#15]
Hi @indigoxela 👋🏽 

I will attempt to revise/rewrite some of the entity definition and controller for the configuration entity that defines bundles for the `entityform` entity. While you found a way to make it work, I think some of the stuff related to the configuration entity deifnition and controller doesn't look right. 

I may not be able to finish this tonight, but I'll try to provide a PR for your consideration.

**Comment by argiepiano** [comment]
@indigoxela, the changes are really minimal, but the change in the controller class for the configuration/bundle-defining entity seems to have done the trick.

**Comment by indigoxela** [comment]
Nice! Who would have thought, that EntityPlusControllerExportable would just do the trick? :smile: Edit: but does it really?

One concern: the change seems incomplete, as currently `$this->id` != `$this->id()`. One returns the serial id field from db, the other returns the machine name ("type").

And if I try to make that consistent in class EntityformType, fields don't get attached to entitforms anymore - _exactly_ what I've been struggling with the past few days.

**Comment by argiepiano** [comment]
@indigoxela I'm not very clear about what you've been struggling with. Can you please clarify? I'm willing to try to help.

Can you post steps to reproduce the problem you are experiencing? In my testing last night, after this change, the entityform UI,  creation, adding field with UI etc, seemed to work fine, so I'm a little lost about exactly where the problem happens and what it is.

**Comment by argiepiano** [comment]
As for `$this->id()`: the entity class method `id()` did not exist in D7 Entity API, so it's very possible that this is a problem created by the new environment... but I'll wait for more information from you about the problem created by this, which I don't yet understand.

**Comment by indigoxela** [comment]
> I'll wait for more information from you about the problem created by this

What is "this"? :wink: 

OK, my findings with your PR are:

1. Switching the base class doesn't change anything noticeable for me
2. Your PR creates an inconsistency, as hook_entity_info now declares "id" as entity key for the id, while the method id(), which is supposed to be a wrapper to access the property "id", still returns "type". That's what I meant with `this->id != this->id()`

Function entity_view (from parent class) works with id() - the method. That's why attaching files wouldn't work, if method id() returned id and not type.

When does this strike? Currently not at all. Without the PR both, id and id() return the type (my trick to fix things). Which means that entity_view still is able to load what's needed.

Problems I had when playing with id-vs-type setting and method values:

- Attempt to submit values fails on eform/submit/TYPE, as no fields could be determined, the form is empty
- Attempt to delete an entityform_type silently fails (types aren't deletable)
- Attempt to clone an entityform_type causes trouble
- Attempt to view an existing, previously created entityform (instance) causes trouble

Currently, with your patch applied, things seem to work. But I don't think that the introduced inconsistency is really an improvement to using "type" consistently.

**Comment by indigoxela** [comment]
And FTR, yes, of course the problem is caused by the differences between D7 entity module and B entity handling.

That's why porting this module is so tricky. :wink:

**Comment by argiepiano** [comment]
> Currently, with your patch applied, things seem to work. But I don't think that the introduced inconsistency is really an improvement to using "type" consistently.

@indigoxela, glad to hear that the patch I submitted solved the issue (kind of). 

Yes, the `Entity` class and the `id()` method won't work as expected with configuration entities, becase (1) the `id()` method did not exist in Entity API, and (2) those types of entities do not exist in Backdrop (they were introduced by Entity API, and Backdrop deviated from it in substantial ways).  The `id()` method introduced in Backdrop did not "foresee" the use of configuration entities.

The solution, is to extend Backdrop's `Entity` class in a way that catches this inconsistency and provides an `id()` method that returns the correct, expected value, and to use that new class for the configuration entity needed here.

I get the feeling that you are all set and happy with your current solution of assigning `type` to the configuration entity id.  That's fine by me. Just "call" if you want any additional feedback or help with this in the future.
